name: Deploy Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 部署网站
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: 构建网站
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./build/*"
          target: "/www/wwwroot/www.halfmillion.cn"
          strip_components: 1

      # 目前较为流行部署到GitHubPages 的Action：
      # 文档: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: 部署到GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 构建输出以发布到 `gh-pages` 分支：
          publish_dir: ./build
          # 将提交作者身份分配给官方 GH-Actions 机器人以部署到 `gh-pages` 分支：
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # 如果您未指定这两个字段，则默认使用 GH 操作机器人。
          # 您可以使用自己的用户凭据替换它们。
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
